package net.suncaper.hotel_manager.domain;

public class H_Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_admin.a_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private Integer aId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_admin.hotel_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private Integer hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_admin.a_account
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String aAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_admin.a_password
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String aPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_admin.a_permission
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String aPermission;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_admin.a_id
     *
     * @return the value of h_admin.a_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Integer getaId() {
        return aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_admin.a_id
     *
     * @param aId the value for h_admin.a_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setaId(Integer aId) {
        this.aId = aId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_admin.hotel_id
     *
     * @return the value of h_admin.hotel_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_admin.hotel_id
     *
     * @param hotelId the value for h_admin.hotel_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_admin.a_account
     *
     * @return the value of h_admin.a_account
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getaAccount() {
        return aAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_admin.a_account
     *
     * @param aAccount the value for h_admin.a_account
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setaAccount(String aAccount) {
        this.aAccount = aAccount == null ? null : aAccount.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_admin.a_password
     *
     * @return the value of h_admin.a_password
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getaPassword() {
        return aPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_admin.a_password
     *
     * @param aPassword the value for h_admin.a_password
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setaPassword(String aPassword) {
        this.aPassword = aPassword == null ? null : aPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_admin.a_permission
     *
     * @return the value of h_admin.a_permission
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getaPermission() {
        return aPermission;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_admin.a_permission
     *
     * @param aPermission the value for h_admin.a_permission
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setaPermission(String aPermission) {
        this.aPermission = aPermission == null ? null : aPermission.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        H_Admin other = (H_Admin) that;
        return (this.getaId() == null ? other.getaId() == null : this.getaId().equals(other.getaId()))
            && (this.getHotelId() == null ? other.getHotelId() == null : this.getHotelId().equals(other.getHotelId()))
            && (this.getaAccount() == null ? other.getaAccount() == null : this.getaAccount().equals(other.getaAccount()))
            && (this.getaPassword() == null ? other.getaPassword() == null : this.getaPassword().equals(other.getaPassword()))
            && (this.getaPermission() == null ? other.getaPermission() == null : this.getaPermission().equals(other.getaPermission()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getaId() == null) ? 0 : getaId().hashCode());
        result = prime * result + ((getHotelId() == null) ? 0 : getHotelId().hashCode());
        result = prime * result + ((getaAccount() == null) ? 0 : getaAccount().hashCode());
        result = prime * result + ((getaPassword() == null) ? 0 : getaPassword().hashCode());
        result = prime * result + ((getaPermission() == null) ? 0 : getaPermission().hashCode());
        return result;
    }
}