package net.suncaper.hotel_manager.domain;

public class H_Hotel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.hotel_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private Integer hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.chain_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private Integer chainId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.chain_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String chainName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.brand_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private Integer brandId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.brand_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String brandName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.hotel_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String hotelName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.hotel_translated_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String hotelTranslatedName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.addressline
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String addressline;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.city
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.state
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.country
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String country;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.star_rating
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String starRating;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.longitude
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String longitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.latitude
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String latitude;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.url
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.numberrooms
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private Integer numberrooms;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.numberfloor
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private Integer numberfloor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.yearopened
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String yearopened;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.photo1
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String photo1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.photo2
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String photo2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.photo3
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String photo3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.rating_average
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String ratingAverage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_hotel.overview
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String overview;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.hotel_id
     *
     * @return the value of h_hotel.hotel_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.hotel_id
     *
     * @param hotelId the value for h_hotel.hotel_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.chain_id
     *
     * @return the value of h_hotel.chain_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Integer getChainId() {
        return chainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.chain_id
     *
     * @param chainId the value for h_hotel.chain_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setChainId(Integer chainId) {
        this.chainId = chainId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.chain_name
     *
     * @return the value of h_hotel.chain_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getChainName() {
        return chainName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.chain_name
     *
     * @param chainName the value for h_hotel.chain_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setChainName(String chainName) {
        this.chainName = chainName == null ? null : chainName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.brand_id
     *
     * @return the value of h_hotel.brand_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Integer getBrandId() {
        return brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.brand_id
     *
     * @param brandId the value for h_hotel.brand_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setBrandId(Integer brandId) {
        this.brandId = brandId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.brand_name
     *
     * @return the value of h_hotel.brand_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getBrandName() {
        return brandName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.brand_name
     *
     * @param brandName the value for h_hotel.brand_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setBrandName(String brandName) {
        this.brandName = brandName == null ? null : brandName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.hotel_name
     *
     * @return the value of h_hotel.hotel_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getHotelName() {
        return hotelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.hotel_name
     *
     * @param hotelName the value for h_hotel.hotel_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setHotelName(String hotelName) {
        this.hotelName = hotelName == null ? null : hotelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.hotel_translated_name
     *
     * @return the value of h_hotel.hotel_translated_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getHotelTranslatedName() {
        return hotelTranslatedName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.hotel_translated_name
     *
     * @param hotelTranslatedName the value for h_hotel.hotel_translated_name
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setHotelTranslatedName(String hotelTranslatedName) {
        this.hotelTranslatedName = hotelTranslatedName == null ? null : hotelTranslatedName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.addressline
     *
     * @return the value of h_hotel.addressline
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getAddressline() {
        return addressline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.addressline
     *
     * @param addressline the value for h_hotel.addressline
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setAddressline(String addressline) {
        this.addressline = addressline == null ? null : addressline.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.city
     *
     * @return the value of h_hotel.city
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.city
     *
     * @param city the value for h_hotel.city
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setCity(String city) {
        this.city = city == null ? null : city.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.state
     *
     * @return the value of h_hotel.state
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.state
     *
     * @param state the value for h_hotel.state
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setState(String state) {
        this.state = state == null ? null : state.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.country
     *
     * @return the value of h_hotel.country
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getCountry() {
        return country;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.country
     *
     * @param country the value for h_hotel.country
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setCountry(String country) {
        this.country = country == null ? null : country.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.star_rating
     *
     * @return the value of h_hotel.star_rating
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getStarRating() {
        return starRating;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.star_rating
     *
     * @param starRating the value for h_hotel.star_rating
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setStarRating(String starRating) {
        this.starRating = starRating == null ? null : starRating.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.longitude
     *
     * @return the value of h_hotel.longitude
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getLongitude() {
        return longitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.longitude
     *
     * @param longitude the value for h_hotel.longitude
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setLongitude(String longitude) {
        this.longitude = longitude == null ? null : longitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.latitude
     *
     * @return the value of h_hotel.latitude
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getLatitude() {
        return latitude;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.latitude
     *
     * @param latitude the value for h_hotel.latitude
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setLatitude(String latitude) {
        this.latitude = latitude == null ? null : latitude.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.url
     *
     * @return the value of h_hotel.url
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.url
     *
     * @param url the value for h_hotel.url
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.numberrooms
     *
     * @return the value of h_hotel.numberrooms
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Integer getNumberrooms() {
        return numberrooms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.numberrooms
     *
     * @param numberrooms the value for h_hotel.numberrooms
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setNumberrooms(Integer numberrooms) {
        this.numberrooms = numberrooms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.numberfloor
     *
     * @return the value of h_hotel.numberfloor
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Integer getNumberfloor() {
        return numberfloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.numberfloor
     *
     * @param numberfloor the value for h_hotel.numberfloor
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setNumberfloor(Integer numberfloor) {
        this.numberfloor = numberfloor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.yearopened
     *
     * @return the value of h_hotel.yearopened
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getYearopened() {
        return yearopened;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.yearopened
     *
     * @param yearopened the value for h_hotel.yearopened
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setYearopened(String yearopened) {
        this.yearopened = yearopened == null ? null : yearopened.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.photo1
     *
     * @return the value of h_hotel.photo1
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getPhoto1() {
        return photo1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.photo1
     *
     * @param photo1 the value for h_hotel.photo1
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setPhoto1(String photo1) {
        this.photo1 = photo1 == null ? null : photo1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.photo2
     *
     * @return the value of h_hotel.photo2
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getPhoto2() {
        return photo2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.photo2
     *
     * @param photo2 the value for h_hotel.photo2
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setPhoto2(String photo2) {
        this.photo2 = photo2 == null ? null : photo2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.photo3
     *
     * @return the value of h_hotel.photo3
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getPhoto3() {
        return photo3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.photo3
     *
     * @param photo3 the value for h_hotel.photo3
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setPhoto3(String photo3) {
        this.photo3 = photo3 == null ? null : photo3.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.rating_average
     *
     * @return the value of h_hotel.rating_average
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getRatingAverage() {
        return ratingAverage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.rating_average
     *
     * @param ratingAverage the value for h_hotel.rating_average
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setRatingAverage(String ratingAverage) {
        this.ratingAverage = ratingAverage == null ? null : ratingAverage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_hotel.overview
     *
     * @return the value of h_hotel.overview
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getOverview() {
        return overview;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_hotel.overview
     *
     * @param overview the value for h_hotel.overview
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setOverview(String overview) {
        this.overview = overview == null ? null : overview.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        H_Hotel other = (H_Hotel) that;
        return (this.getHotelId() == null ? other.getHotelId() == null : this.getHotelId().equals(other.getHotelId()))
            && (this.getChainId() == null ? other.getChainId() == null : this.getChainId().equals(other.getChainId()))
            && (this.getChainName() == null ? other.getChainName() == null : this.getChainName().equals(other.getChainName()))
            && (this.getBrandId() == null ? other.getBrandId() == null : this.getBrandId().equals(other.getBrandId()))
            && (this.getBrandName() == null ? other.getBrandName() == null : this.getBrandName().equals(other.getBrandName()))
            && (this.getHotelName() == null ? other.getHotelName() == null : this.getHotelName().equals(other.getHotelName()))
            && (this.getHotelTranslatedName() == null ? other.getHotelTranslatedName() == null : this.getHotelTranslatedName().equals(other.getHotelTranslatedName()))
            && (this.getAddressline() == null ? other.getAddressline() == null : this.getAddressline().equals(other.getAddressline()))
            && (this.getCity() == null ? other.getCity() == null : this.getCity().equals(other.getCity()))
            && (this.getState() == null ? other.getState() == null : this.getState().equals(other.getState()))
            && (this.getCountry() == null ? other.getCountry() == null : this.getCountry().equals(other.getCountry()))
            && (this.getStarRating() == null ? other.getStarRating() == null : this.getStarRating().equals(other.getStarRating()))
            && (this.getLongitude() == null ? other.getLongitude() == null : this.getLongitude().equals(other.getLongitude()))
            && (this.getLatitude() == null ? other.getLatitude() == null : this.getLatitude().equals(other.getLatitude()))
            && (this.getUrl() == null ? other.getUrl() == null : this.getUrl().equals(other.getUrl()))
            && (this.getNumberrooms() == null ? other.getNumberrooms() == null : this.getNumberrooms().equals(other.getNumberrooms()))
            && (this.getNumberfloor() == null ? other.getNumberfloor() == null : this.getNumberfloor().equals(other.getNumberfloor()))
            && (this.getYearopened() == null ? other.getYearopened() == null : this.getYearopened().equals(other.getYearopened()))
            && (this.getPhoto1() == null ? other.getPhoto1() == null : this.getPhoto1().equals(other.getPhoto1()))
            && (this.getPhoto2() == null ? other.getPhoto2() == null : this.getPhoto2().equals(other.getPhoto2()))
            && (this.getPhoto3() == null ? other.getPhoto3() == null : this.getPhoto3().equals(other.getPhoto3()))
            && (this.getRatingAverage() == null ? other.getRatingAverage() == null : this.getRatingAverage().equals(other.getRatingAverage()))
            && (this.getOverview() == null ? other.getOverview() == null : this.getOverview().equals(other.getOverview()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHotelId() == null) ? 0 : getHotelId().hashCode());
        result = prime * result + ((getChainId() == null) ? 0 : getChainId().hashCode());
        result = prime * result + ((getChainName() == null) ? 0 : getChainName().hashCode());
        result = prime * result + ((getBrandId() == null) ? 0 : getBrandId().hashCode());
        result = prime * result + ((getBrandName() == null) ? 0 : getBrandName().hashCode());
        result = prime * result + ((getHotelName() == null) ? 0 : getHotelName().hashCode());
        result = prime * result + ((getHotelTranslatedName() == null) ? 0 : getHotelTranslatedName().hashCode());
        result = prime * result + ((getAddressline() == null) ? 0 : getAddressline().hashCode());
        result = prime * result + ((getCity() == null) ? 0 : getCity().hashCode());
        result = prime * result + ((getState() == null) ? 0 : getState().hashCode());
        result = prime * result + ((getCountry() == null) ? 0 : getCountry().hashCode());
        result = prime * result + ((getStarRating() == null) ? 0 : getStarRating().hashCode());
        result = prime * result + ((getLongitude() == null) ? 0 : getLongitude().hashCode());
        result = prime * result + ((getLatitude() == null) ? 0 : getLatitude().hashCode());
        result = prime * result + ((getUrl() == null) ? 0 : getUrl().hashCode());
        result = prime * result + ((getNumberrooms() == null) ? 0 : getNumberrooms().hashCode());
        result = prime * result + ((getNumberfloor() == null) ? 0 : getNumberfloor().hashCode());
        result = prime * result + ((getYearopened() == null) ? 0 : getYearopened().hashCode());
        result = prime * result + ((getPhoto1() == null) ? 0 : getPhoto1().hashCode());
        result = prime * result + ((getPhoto2() == null) ? 0 : getPhoto2().hashCode());
        result = prime * result + ((getPhoto3() == null) ? 0 : getPhoto3().hashCode());
        result = prime * result + ((getRatingAverage() == null) ? 0 : getRatingAverage().hashCode());
        result = prime * result + ((getOverview() == null) ? 0 : getOverview().hashCode());
        return result;
    }
}