package net.suncaper.hotel_manager.domain;

import java.util.ArrayList;
import java.util.List;

public class H_HotelExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public H_HotelExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andHotelIdIsNull() {
            addCriterion("hotel_id is null");
            return (Criteria) this;
        }

        public Criteria andHotelIdIsNotNull() {
            addCriterion("hotel_id is not null");
            return (Criteria) this;
        }

        public Criteria andHotelIdEqualTo(Integer value) {
            addCriterion("hotel_id =", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotEqualTo(Integer value) {
            addCriterion("hotel_id <>", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThan(Integer value) {
            addCriterion("hotel_id >", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("hotel_id >=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThan(Integer value) {
            addCriterion("hotel_id <", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdLessThanOrEqualTo(Integer value) {
            addCriterion("hotel_id <=", value, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdIn(List<Integer> values) {
            addCriterion("hotel_id in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotIn(List<Integer> values) {
            addCriterion("hotel_id not in", values, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdBetween(Integer value1, Integer value2) {
            addCriterion("hotel_id between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andHotelIdNotBetween(Integer value1, Integer value2) {
            addCriterion("hotel_id not between", value1, value2, "hotelId");
            return (Criteria) this;
        }

        public Criteria andChainIdIsNull() {
            addCriterion("chain_id is null");
            return (Criteria) this;
        }

        public Criteria andChainIdIsNotNull() {
            addCriterion("chain_id is not null");
            return (Criteria) this;
        }

        public Criteria andChainIdEqualTo(Integer value) {
            addCriterion("chain_id =", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdNotEqualTo(Integer value) {
            addCriterion("chain_id <>", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdGreaterThan(Integer value) {
            addCriterion("chain_id >", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("chain_id >=", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdLessThan(Integer value) {
            addCriterion("chain_id <", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdLessThanOrEqualTo(Integer value) {
            addCriterion("chain_id <=", value, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdIn(List<Integer> values) {
            addCriterion("chain_id in", values, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdNotIn(List<Integer> values) {
            addCriterion("chain_id not in", values, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdBetween(Integer value1, Integer value2) {
            addCriterion("chain_id between", value1, value2, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainIdNotBetween(Integer value1, Integer value2) {
            addCriterion("chain_id not between", value1, value2, "chainId");
            return (Criteria) this;
        }

        public Criteria andChainNameIsNull() {
            addCriterion("chain_name is null");
            return (Criteria) this;
        }

        public Criteria andChainNameIsNotNull() {
            addCriterion("chain_name is not null");
            return (Criteria) this;
        }

        public Criteria andChainNameEqualTo(String value) {
            addCriterion("chain_name =", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameNotEqualTo(String value) {
            addCriterion("chain_name <>", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameGreaterThan(String value) {
            addCriterion("chain_name >", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameGreaterThanOrEqualTo(String value) {
            addCriterion("chain_name >=", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameLessThan(String value) {
            addCriterion("chain_name <", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameLessThanOrEqualTo(String value) {
            addCriterion("chain_name <=", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameLike(String value) {
            addCriterion("chain_name like", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameNotLike(String value) {
            addCriterion("chain_name not like", value, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameIn(List<String> values) {
            addCriterion("chain_name in", values, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameNotIn(List<String> values) {
            addCriterion("chain_name not in", values, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameBetween(String value1, String value2) {
            addCriterion("chain_name between", value1, value2, "chainName");
            return (Criteria) this;
        }

        public Criteria andChainNameNotBetween(String value1, String value2) {
            addCriterion("chain_name not between", value1, value2, "chainName");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNull() {
            addCriterion("brand_id is null");
            return (Criteria) this;
        }

        public Criteria andBrandIdIsNotNull() {
            addCriterion("brand_id is not null");
            return (Criteria) this;
        }

        public Criteria andBrandIdEqualTo(Integer value) {
            addCriterion("brand_id =", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotEqualTo(Integer value) {
            addCriterion("brand_id <>", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThan(Integer value) {
            addCriterion("brand_id >", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("brand_id >=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThan(Integer value) {
            addCriterion("brand_id <", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdLessThanOrEqualTo(Integer value) {
            addCriterion("brand_id <=", value, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdIn(List<Integer> values) {
            addCriterion("brand_id in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotIn(List<Integer> values) {
            addCriterion("brand_id not in", values, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdBetween(Integer value1, Integer value2) {
            addCriterion("brand_id between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandIdNotBetween(Integer value1, Integer value2) {
            addCriterion("brand_id not between", value1, value2, "brandId");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNull() {
            addCriterion("brand_name is null");
            return (Criteria) this;
        }

        public Criteria andBrandNameIsNotNull() {
            addCriterion("brand_name is not null");
            return (Criteria) this;
        }

        public Criteria andBrandNameEqualTo(String value) {
            addCriterion("brand_name =", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotEqualTo(String value) {
            addCriterion("brand_name <>", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThan(String value) {
            addCriterion("brand_name >", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameGreaterThanOrEqualTo(String value) {
            addCriterion("brand_name >=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThan(String value) {
            addCriterion("brand_name <", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLessThanOrEqualTo(String value) {
            addCriterion("brand_name <=", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameLike(String value) {
            addCriterion("brand_name like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotLike(String value) {
            addCriterion("brand_name not like", value, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameIn(List<String> values) {
            addCriterion("brand_name in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotIn(List<String> values) {
            addCriterion("brand_name not in", values, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameBetween(String value1, String value2) {
            addCriterion("brand_name between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andBrandNameNotBetween(String value1, String value2) {
            addCriterion("brand_name not between", value1, value2, "brandName");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNull() {
            addCriterion("hotel_name is null");
            return (Criteria) this;
        }

        public Criteria andHotelNameIsNotNull() {
            addCriterion("hotel_name is not null");
            return (Criteria) this;
        }

        public Criteria andHotelNameEqualTo(String value) {
            addCriterion("hotel_name =", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotEqualTo(String value) {
            addCriterion("hotel_name <>", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThan(String value) {
            addCriterion("hotel_name >", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_name >=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThan(String value) {
            addCriterion("hotel_name <", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLessThanOrEqualTo(String value) {
            addCriterion("hotel_name <=", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameLike(String value) {
            addCriterion("hotel_name like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotLike(String value) {
            addCriterion("hotel_name not like", value, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameIn(List<String> values) {
            addCriterion("hotel_name in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotIn(List<String> values) {
            addCriterion("hotel_name not in", values, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameBetween(String value1, String value2) {
            addCriterion("hotel_name between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelNameNotBetween(String value1, String value2) {
            addCriterion("hotel_name not between", value1, value2, "hotelName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameIsNull() {
            addCriterion("hotel_translated_name is null");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameIsNotNull() {
            addCriterion("hotel_translated_name is not null");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameEqualTo(String value) {
            addCriterion("hotel_translated_name =", value, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameNotEqualTo(String value) {
            addCriterion("hotel_translated_name <>", value, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameGreaterThan(String value) {
            addCriterion("hotel_translated_name >", value, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameGreaterThanOrEqualTo(String value) {
            addCriterion("hotel_translated_name >=", value, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameLessThan(String value) {
            addCriterion("hotel_translated_name <", value, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameLessThanOrEqualTo(String value) {
            addCriterion("hotel_translated_name <=", value, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameLike(String value) {
            addCriterion("hotel_translated_name like", value, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameNotLike(String value) {
            addCriterion("hotel_translated_name not like", value, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameIn(List<String> values) {
            addCriterion("hotel_translated_name in", values, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameNotIn(List<String> values) {
            addCriterion("hotel_translated_name not in", values, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameBetween(String value1, String value2) {
            addCriterion("hotel_translated_name between", value1, value2, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andHotelTranslatedNameNotBetween(String value1, String value2) {
            addCriterion("hotel_translated_name not between", value1, value2, "hotelTranslatedName");
            return (Criteria) this;
        }

        public Criteria andAddresslineIsNull() {
            addCriterion("addressline is null");
            return (Criteria) this;
        }

        public Criteria andAddresslineIsNotNull() {
            addCriterion("addressline is not null");
            return (Criteria) this;
        }

        public Criteria andAddresslineEqualTo(String value) {
            addCriterion("addressline =", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineNotEqualTo(String value) {
            addCriterion("addressline <>", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineGreaterThan(String value) {
            addCriterion("addressline >", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineGreaterThanOrEqualTo(String value) {
            addCriterion("addressline >=", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineLessThan(String value) {
            addCriterion("addressline <", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineLessThanOrEqualTo(String value) {
            addCriterion("addressline <=", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineLike(String value) {
            addCriterion("addressline like", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineNotLike(String value) {
            addCriterion("addressline not like", value, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineIn(List<String> values) {
            addCriterion("addressline in", values, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineNotIn(List<String> values) {
            addCriterion("addressline not in", values, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineBetween(String value1, String value2) {
            addCriterion("addressline between", value1, value2, "addressline");
            return (Criteria) this;
        }

        public Criteria andAddresslineNotBetween(String value1, String value2) {
            addCriterion("addressline not between", value1, value2, "addressline");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(String value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(String value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(String value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(String value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(String value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(String value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLike(String value) {
            addCriterion("state like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotLike(String value) {
            addCriterion("state not like", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<String> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<String> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(String value1, String value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(String value1, String value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andCountryIsNull() {
            addCriterion("country is null");
            return (Criteria) this;
        }

        public Criteria andCountryIsNotNull() {
            addCriterion("country is not null");
            return (Criteria) this;
        }

        public Criteria andCountryEqualTo(String value) {
            addCriterion("country =", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotEqualTo(String value) {
            addCriterion("country <>", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThan(String value) {
            addCriterion("country >", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryGreaterThanOrEqualTo(String value) {
            addCriterion("country >=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThan(String value) {
            addCriterion("country <", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLessThanOrEqualTo(String value) {
            addCriterion("country <=", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryLike(String value) {
            addCriterion("country like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotLike(String value) {
            addCriterion("country not like", value, "country");
            return (Criteria) this;
        }

        public Criteria andCountryIn(List<String> values) {
            addCriterion("country in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotIn(List<String> values) {
            addCriterion("country not in", values, "country");
            return (Criteria) this;
        }

        public Criteria andCountryBetween(String value1, String value2) {
            addCriterion("country between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andCountryNotBetween(String value1, String value2) {
            addCriterion("country not between", value1, value2, "country");
            return (Criteria) this;
        }

        public Criteria andStarRatingIsNull() {
            addCriterion("star_rating is null");
            return (Criteria) this;
        }

        public Criteria andStarRatingIsNotNull() {
            addCriterion("star_rating is not null");
            return (Criteria) this;
        }

        public Criteria andStarRatingEqualTo(String value) {
            addCriterion("star_rating =", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingNotEqualTo(String value) {
            addCriterion("star_rating <>", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingGreaterThan(String value) {
            addCriterion("star_rating >", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingGreaterThanOrEqualTo(String value) {
            addCriterion("star_rating >=", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingLessThan(String value) {
            addCriterion("star_rating <", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingLessThanOrEqualTo(String value) {
            addCriterion("star_rating <=", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingLike(String value) {
            addCriterion("star_rating like", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingNotLike(String value) {
            addCriterion("star_rating not like", value, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingIn(List<String> values) {
            addCriterion("star_rating in", values, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingNotIn(List<String> values) {
            addCriterion("star_rating not in", values, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingBetween(String value1, String value2) {
            addCriterion("star_rating between", value1, value2, "starRating");
            return (Criteria) this;
        }

        public Criteria andStarRatingNotBetween(String value1, String value2) {
            addCriterion("star_rating not between", value1, value2, "starRating");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNull() {
            addCriterion("longitude is null");
            return (Criteria) this;
        }

        public Criteria andLongitudeIsNotNull() {
            addCriterion("longitude is not null");
            return (Criteria) this;
        }

        public Criteria andLongitudeEqualTo(String value) {
            addCriterion("longitude =", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotEqualTo(String value) {
            addCriterion("longitude <>", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThan(String value) {
            addCriterion("longitude >", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeGreaterThanOrEqualTo(String value) {
            addCriterion("longitude >=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThan(String value) {
            addCriterion("longitude <", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLessThanOrEqualTo(String value) {
            addCriterion("longitude <=", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeLike(String value) {
            addCriterion("longitude like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotLike(String value) {
            addCriterion("longitude not like", value, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeIn(List<String> values) {
            addCriterion("longitude in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotIn(List<String> values) {
            addCriterion("longitude not in", values, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeBetween(String value1, String value2) {
            addCriterion("longitude between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLongitudeNotBetween(String value1, String value2) {
            addCriterion("longitude not between", value1, value2, "longitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNull() {
            addCriterion("latitude is null");
            return (Criteria) this;
        }

        public Criteria andLatitudeIsNotNull() {
            addCriterion("latitude is not null");
            return (Criteria) this;
        }

        public Criteria andLatitudeEqualTo(String value) {
            addCriterion("latitude =", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotEqualTo(String value) {
            addCriterion("latitude <>", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThan(String value) {
            addCriterion("latitude >", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeGreaterThanOrEqualTo(String value) {
            addCriterion("latitude >=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThan(String value) {
            addCriterion("latitude <", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLessThanOrEqualTo(String value) {
            addCriterion("latitude <=", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeLike(String value) {
            addCriterion("latitude like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotLike(String value) {
            addCriterion("latitude not like", value, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeIn(List<String> values) {
            addCriterion("latitude in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotIn(List<String> values) {
            addCriterion("latitude not in", values, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeBetween(String value1, String value2) {
            addCriterion("latitude between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andLatitudeNotBetween(String value1, String value2) {
            addCriterion("latitude not between", value1, value2, "latitude");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andNumberroomsIsNull() {
            addCriterion("numberrooms is null");
            return (Criteria) this;
        }

        public Criteria andNumberroomsIsNotNull() {
            addCriterion("numberrooms is not null");
            return (Criteria) this;
        }

        public Criteria andNumberroomsEqualTo(Integer value) {
            addCriterion("numberrooms =", value, "numberrooms");
            return (Criteria) this;
        }

        public Criteria andNumberroomsNotEqualTo(Integer value) {
            addCriterion("numberrooms <>", value, "numberrooms");
            return (Criteria) this;
        }

        public Criteria andNumberroomsGreaterThan(Integer value) {
            addCriterion("numberrooms >", value, "numberrooms");
            return (Criteria) this;
        }

        public Criteria andNumberroomsGreaterThanOrEqualTo(Integer value) {
            addCriterion("numberrooms >=", value, "numberrooms");
            return (Criteria) this;
        }

        public Criteria andNumberroomsLessThan(Integer value) {
            addCriterion("numberrooms <", value, "numberrooms");
            return (Criteria) this;
        }

        public Criteria andNumberroomsLessThanOrEqualTo(Integer value) {
            addCriterion("numberrooms <=", value, "numberrooms");
            return (Criteria) this;
        }

        public Criteria andNumberroomsIn(List<Integer> values) {
            addCriterion("numberrooms in", values, "numberrooms");
            return (Criteria) this;
        }

        public Criteria andNumberroomsNotIn(List<Integer> values) {
            addCriterion("numberrooms not in", values, "numberrooms");
            return (Criteria) this;
        }

        public Criteria andNumberroomsBetween(Integer value1, Integer value2) {
            addCriterion("numberrooms between", value1, value2, "numberrooms");
            return (Criteria) this;
        }

        public Criteria andNumberroomsNotBetween(Integer value1, Integer value2) {
            addCriterion("numberrooms not between", value1, value2, "numberrooms");
            return (Criteria) this;
        }

        public Criteria andNumberfloorIsNull() {
            addCriterion("numberfloor is null");
            return (Criteria) this;
        }

        public Criteria andNumberfloorIsNotNull() {
            addCriterion("numberfloor is not null");
            return (Criteria) this;
        }

        public Criteria andNumberfloorEqualTo(Integer value) {
            addCriterion("numberfloor =", value, "numberfloor");
            return (Criteria) this;
        }

        public Criteria andNumberfloorNotEqualTo(Integer value) {
            addCriterion("numberfloor <>", value, "numberfloor");
            return (Criteria) this;
        }

        public Criteria andNumberfloorGreaterThan(Integer value) {
            addCriterion("numberfloor >", value, "numberfloor");
            return (Criteria) this;
        }

        public Criteria andNumberfloorGreaterThanOrEqualTo(Integer value) {
            addCriterion("numberfloor >=", value, "numberfloor");
            return (Criteria) this;
        }

        public Criteria andNumberfloorLessThan(Integer value) {
            addCriterion("numberfloor <", value, "numberfloor");
            return (Criteria) this;
        }

        public Criteria andNumberfloorLessThanOrEqualTo(Integer value) {
            addCriterion("numberfloor <=", value, "numberfloor");
            return (Criteria) this;
        }

        public Criteria andNumberfloorIn(List<Integer> values) {
            addCriterion("numberfloor in", values, "numberfloor");
            return (Criteria) this;
        }

        public Criteria andNumberfloorNotIn(List<Integer> values) {
            addCriterion("numberfloor not in", values, "numberfloor");
            return (Criteria) this;
        }

        public Criteria andNumberfloorBetween(Integer value1, Integer value2) {
            addCriterion("numberfloor between", value1, value2, "numberfloor");
            return (Criteria) this;
        }

        public Criteria andNumberfloorNotBetween(Integer value1, Integer value2) {
            addCriterion("numberfloor not between", value1, value2, "numberfloor");
            return (Criteria) this;
        }

        public Criteria andYearopenedIsNull() {
            addCriterion("yearopened is null");
            return (Criteria) this;
        }

        public Criteria andYearopenedIsNotNull() {
            addCriterion("yearopened is not null");
            return (Criteria) this;
        }

        public Criteria andYearopenedEqualTo(String value) {
            addCriterion("yearopened =", value, "yearopened");
            return (Criteria) this;
        }

        public Criteria andYearopenedNotEqualTo(String value) {
            addCriterion("yearopened <>", value, "yearopened");
            return (Criteria) this;
        }

        public Criteria andYearopenedGreaterThan(String value) {
            addCriterion("yearopened >", value, "yearopened");
            return (Criteria) this;
        }

        public Criteria andYearopenedGreaterThanOrEqualTo(String value) {
            addCriterion("yearopened >=", value, "yearopened");
            return (Criteria) this;
        }

        public Criteria andYearopenedLessThan(String value) {
            addCriterion("yearopened <", value, "yearopened");
            return (Criteria) this;
        }

        public Criteria andYearopenedLessThanOrEqualTo(String value) {
            addCriterion("yearopened <=", value, "yearopened");
            return (Criteria) this;
        }

        public Criteria andYearopenedLike(String value) {
            addCriterion("yearopened like", value, "yearopened");
            return (Criteria) this;
        }

        public Criteria andYearopenedNotLike(String value) {
            addCriterion("yearopened not like", value, "yearopened");
            return (Criteria) this;
        }

        public Criteria andYearopenedIn(List<String> values) {
            addCriterion("yearopened in", values, "yearopened");
            return (Criteria) this;
        }

        public Criteria andYearopenedNotIn(List<String> values) {
            addCriterion("yearopened not in", values, "yearopened");
            return (Criteria) this;
        }

        public Criteria andYearopenedBetween(String value1, String value2) {
            addCriterion("yearopened between", value1, value2, "yearopened");
            return (Criteria) this;
        }

        public Criteria andYearopenedNotBetween(String value1, String value2) {
            addCriterion("yearopened not between", value1, value2, "yearopened");
            return (Criteria) this;
        }

        public Criteria andPhoto1IsNull() {
            addCriterion("photo1 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto1IsNotNull() {
            addCriterion("photo1 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto1EqualTo(String value) {
            addCriterion("photo1 =", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotEqualTo(String value) {
            addCriterion("photo1 <>", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1GreaterThan(String value) {
            addCriterion("photo1 >", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1GreaterThanOrEqualTo(String value) {
            addCriterion("photo1 >=", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1LessThan(String value) {
            addCriterion("photo1 <", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1LessThanOrEqualTo(String value) {
            addCriterion("photo1 <=", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1Like(String value) {
            addCriterion("photo1 like", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotLike(String value) {
            addCriterion("photo1 not like", value, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1In(List<String> values) {
            addCriterion("photo1 in", values, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotIn(List<String> values) {
            addCriterion("photo1 not in", values, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1Between(String value1, String value2) {
            addCriterion("photo1 between", value1, value2, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto1NotBetween(String value1, String value2) {
            addCriterion("photo1 not between", value1, value2, "photo1");
            return (Criteria) this;
        }

        public Criteria andPhoto2IsNull() {
            addCriterion("photo2 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto2IsNotNull() {
            addCriterion("photo2 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto2EqualTo(String value) {
            addCriterion("photo2 =", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotEqualTo(String value) {
            addCriterion("photo2 <>", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2GreaterThan(String value) {
            addCriterion("photo2 >", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2GreaterThanOrEqualTo(String value) {
            addCriterion("photo2 >=", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2LessThan(String value) {
            addCriterion("photo2 <", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2LessThanOrEqualTo(String value) {
            addCriterion("photo2 <=", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2Like(String value) {
            addCriterion("photo2 like", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotLike(String value) {
            addCriterion("photo2 not like", value, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2In(List<String> values) {
            addCriterion("photo2 in", values, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotIn(List<String> values) {
            addCriterion("photo2 not in", values, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2Between(String value1, String value2) {
            addCriterion("photo2 between", value1, value2, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto2NotBetween(String value1, String value2) {
            addCriterion("photo2 not between", value1, value2, "photo2");
            return (Criteria) this;
        }

        public Criteria andPhoto3IsNull() {
            addCriterion("photo3 is null");
            return (Criteria) this;
        }

        public Criteria andPhoto3IsNotNull() {
            addCriterion("photo3 is not null");
            return (Criteria) this;
        }

        public Criteria andPhoto3EqualTo(String value) {
            addCriterion("photo3 =", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotEqualTo(String value) {
            addCriterion("photo3 <>", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3GreaterThan(String value) {
            addCriterion("photo3 >", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3GreaterThanOrEqualTo(String value) {
            addCriterion("photo3 >=", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3LessThan(String value) {
            addCriterion("photo3 <", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3LessThanOrEqualTo(String value) {
            addCriterion("photo3 <=", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3Like(String value) {
            addCriterion("photo3 like", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotLike(String value) {
            addCriterion("photo3 not like", value, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3In(List<String> values) {
            addCriterion("photo3 in", values, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotIn(List<String> values) {
            addCriterion("photo3 not in", values, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3Between(String value1, String value2) {
            addCriterion("photo3 between", value1, value2, "photo3");
            return (Criteria) this;
        }

        public Criteria andPhoto3NotBetween(String value1, String value2) {
            addCriterion("photo3 not between", value1, value2, "photo3");
            return (Criteria) this;
        }

        public Criteria andRatingAverageIsNull() {
            addCriterion("rating_average is null");
            return (Criteria) this;
        }

        public Criteria andRatingAverageIsNotNull() {
            addCriterion("rating_average is not null");
            return (Criteria) this;
        }

        public Criteria andRatingAverageEqualTo(String value) {
            addCriterion("rating_average =", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageNotEqualTo(String value) {
            addCriterion("rating_average <>", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageGreaterThan(String value) {
            addCriterion("rating_average >", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageGreaterThanOrEqualTo(String value) {
            addCriterion("rating_average >=", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageLessThan(String value) {
            addCriterion("rating_average <", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageLessThanOrEqualTo(String value) {
            addCriterion("rating_average <=", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageLike(String value) {
            addCriterion("rating_average like", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageNotLike(String value) {
            addCriterion("rating_average not like", value, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageIn(List<String> values) {
            addCriterion("rating_average in", values, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageNotIn(List<String> values) {
            addCriterion("rating_average not in", values, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageBetween(String value1, String value2) {
            addCriterion("rating_average between", value1, value2, "ratingAverage");
            return (Criteria) this;
        }

        public Criteria andRatingAverageNotBetween(String value1, String value2) {
            addCriterion("rating_average not between", value1, value2, "ratingAverage");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table h_hotel
     *
     * @mbg.generated do_not_delete_during_merge Wed Aug 07 17:59:24 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}