package net.suncaper.hotel_manager.domain;

import java.util.ArrayList;
import java.util.List;

public class H_MangerExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    public H_MangerExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andMIdIsNull() {
            addCriterion("m_id is null");
            return (Criteria) this;
        }

        public Criteria andMIdIsNotNull() {
            addCriterion("m_id is not null");
            return (Criteria) this;
        }

        public Criteria andMIdEqualTo(Integer value) {
            addCriterion("m_id =", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotEqualTo(Integer value) {
            addCriterion("m_id <>", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdGreaterThan(Integer value) {
            addCriterion("m_id >", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("m_id >=", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdLessThan(Integer value) {
            addCriterion("m_id <", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdLessThanOrEqualTo(Integer value) {
            addCriterion("m_id <=", value, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdIn(List<Integer> values) {
            addCriterion("m_id in", values, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotIn(List<Integer> values) {
            addCriterion("m_id not in", values, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdBetween(Integer value1, Integer value2) {
            addCriterion("m_id between", value1, value2, "mId");
            return (Criteria) this;
        }

        public Criteria andMIdNotBetween(Integer value1, Integer value2) {
            addCriterion("m_id not between", value1, value2, "mId");
            return (Criteria) this;
        }

        public Criteria andMAccountIsNull() {
            addCriterion("m_account is null");
            return (Criteria) this;
        }

        public Criteria andMAccountIsNotNull() {
            addCriterion("m_account is not null");
            return (Criteria) this;
        }

        public Criteria andMAccountEqualTo(String value) {
            addCriterion("m_account =", value, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMAccountNotEqualTo(String value) {
            addCriterion("m_account <>", value, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMAccountGreaterThan(String value) {
            addCriterion("m_account >", value, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMAccountGreaterThanOrEqualTo(String value) {
            addCriterion("m_account >=", value, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMAccountLessThan(String value) {
            addCriterion("m_account <", value, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMAccountLessThanOrEqualTo(String value) {
            addCriterion("m_account <=", value, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMAccountLike(String value) {
            addCriterion("m_account like", value, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMAccountNotLike(String value) {
            addCriterion("m_account not like", value, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMAccountIn(List<String> values) {
            addCriterion("m_account in", values, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMAccountNotIn(List<String> values) {
            addCriterion("m_account not in", values, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMAccountBetween(String value1, String value2) {
            addCriterion("m_account between", value1, value2, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMAccountNotBetween(String value1, String value2) {
            addCriterion("m_account not between", value1, value2, "mAccount");
            return (Criteria) this;
        }

        public Criteria andMPassowordIsNull() {
            addCriterion("m_passoword is null");
            return (Criteria) this;
        }

        public Criteria andMPassowordIsNotNull() {
            addCriterion("m_passoword is not null");
            return (Criteria) this;
        }

        public Criteria andMPassowordEqualTo(String value) {
            addCriterion("m_passoword =", value, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPassowordNotEqualTo(String value) {
            addCriterion("m_passoword <>", value, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPassowordGreaterThan(String value) {
            addCriterion("m_passoword >", value, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPassowordGreaterThanOrEqualTo(String value) {
            addCriterion("m_passoword >=", value, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPassowordLessThan(String value) {
            addCriterion("m_passoword <", value, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPassowordLessThanOrEqualTo(String value) {
            addCriterion("m_passoword <=", value, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPassowordLike(String value) {
            addCriterion("m_passoword like", value, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPassowordNotLike(String value) {
            addCriterion("m_passoword not like", value, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPassowordIn(List<String> values) {
            addCriterion("m_passoword in", values, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPassowordNotIn(List<String> values) {
            addCriterion("m_passoword not in", values, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPassowordBetween(String value1, String value2) {
            addCriterion("m_passoword between", value1, value2, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPassowordNotBetween(String value1, String value2) {
            addCriterion("m_passoword not between", value1, value2, "mPassoword");
            return (Criteria) this;
        }

        public Criteria andMPermissionIsNull() {
            addCriterion("m_permission is null");
            return (Criteria) this;
        }

        public Criteria andMPermissionIsNotNull() {
            addCriterion("m_permission is not null");
            return (Criteria) this;
        }

        public Criteria andMPermissionEqualTo(String value) {
            addCriterion("m_permission =", value, "mPermission");
            return (Criteria) this;
        }

        public Criteria andMPermissionNotEqualTo(String value) {
            addCriterion("m_permission <>", value, "mPermission");
            return (Criteria) this;
        }

        public Criteria andMPermissionGreaterThan(String value) {
            addCriterion("m_permission >", value, "mPermission");
            return (Criteria) this;
        }

        public Criteria andMPermissionGreaterThanOrEqualTo(String value) {
            addCriterion("m_permission >=", value, "mPermission");
            return (Criteria) this;
        }

        public Criteria andMPermissionLessThan(String value) {
            addCriterion("m_permission <", value, "mPermission");
            return (Criteria) this;
        }

        public Criteria andMPermissionLessThanOrEqualTo(String value) {
            addCriterion("m_permission <=", value, "mPermission");
            return (Criteria) this;
        }

        public Criteria andMPermissionLike(String value) {
            addCriterion("m_permission like", value, "mPermission");
            return (Criteria) this;
        }

        public Criteria andMPermissionNotLike(String value) {
            addCriterion("m_permission not like", value, "mPermission");
            return (Criteria) this;
        }

        public Criteria andMPermissionIn(List<String> values) {
            addCriterion("m_permission in", values, "mPermission");
            return (Criteria) this;
        }

        public Criteria andMPermissionNotIn(List<String> values) {
            addCriterion("m_permission not in", values, "mPermission");
            return (Criteria) this;
        }

        public Criteria andMPermissionBetween(String value1, String value2) {
            addCriterion("m_permission between", value1, value2, "mPermission");
            return (Criteria) this;
        }

        public Criteria andMPermissionNotBetween(String value1, String value2) {
            addCriterion("m_permission not between", value1, value2, "mPermission");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table h_manager
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 29 16:48:28 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table h_manager
     *
     * @mbg.generated Mon Jul 29 16:48:28 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}