package net.suncaper.hotel_manager.domain;

public class H_Room {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_room.r_id
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    private Integer rId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_room.rt_id
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    private Integer rtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_room.r_number
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    private String rNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_room.r_status
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    private String rStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_room.r_id
     *
     * @return the value of h_room.r_id
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    public Integer getrId() {
        return rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_room.r_id
     *
     * @param rId the value for h_room.r_id
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    public void setrId(Integer rId) {
        this.rId = rId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_room.rt_id
     *
     * @return the value of h_room.rt_id
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    public Integer getRtId() {
        return rtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_room.rt_id
     *
     * @param rtId the value for h_room.rt_id
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    public void setRtId(Integer rtId) {
        this.rtId = rtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_room.r_number
     *
     * @return the value of h_room.r_number
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    public String getrNumber() {
        return rNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_room.r_number
     *
     * @param rNumber the value for h_room.r_number
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    public void setrNumber(String rNumber) {
        this.rNumber = rNumber == null ? null : rNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_room.r_status
     *
     * @return the value of h_room.r_status
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    public String getrStatus() {
        return rStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_room.r_status
     *
     * @param rStatus the value for h_room.r_status
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    public void setrStatus(String rStatus) {
        this.rStatus = rStatus == null ? null : rStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        H_Room other = (H_Room) that;
        return (this.getrId() == null ? other.getrId() == null : this.getrId().equals(other.getrId()))
            && (this.getRtId() == null ? other.getRtId() == null : this.getRtId().equals(other.getRtId()))
            && (this.getrNumber() == null ? other.getrNumber() == null : this.getrNumber().equals(other.getrNumber()))
            && (this.getrStatus() == null ? other.getrStatus() == null : this.getrStatus().equals(other.getrStatus()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Thu Aug 01 14:13:07 GMT+08:00 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getrId() == null) ? 0 : getrId().hashCode());
        result = prime * result + ((getRtId() == null) ? 0 : getRtId().hashCode());
        result = prime * result + ((getrNumber() == null) ? 0 : getrNumber().hashCode());
        result = prime * result + ((getrStatus() == null) ? 0 : getrStatus().hashCode());
        return result;
    }
}