package net.suncaper.hotel_manager.domain;

public class H_Roomtype {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_roomtype.rt_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private Integer rtId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_roomtype.hotel_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private Integer hotelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_roomtype.rt_type
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private String rtType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_roomtype.rt_stock
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private Integer rtStock;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column h_roomtype.rt_price
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    private Integer rtPrice;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_roomtype.rt_id
     *
     * @return the value of h_roomtype.rt_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Integer getRtId() {
        return rtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_roomtype.rt_id
     *
     * @param rtId the value for h_roomtype.rt_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setRtId(Integer rtId) {
        this.rtId = rtId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_roomtype.hotel_id
     *
     * @return the value of h_roomtype.hotel_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Integer getHotelId() {
        return hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_roomtype.hotel_id
     *
     * @param hotelId the value for h_roomtype.hotel_id
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setHotelId(Integer hotelId) {
        this.hotelId = hotelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_roomtype.rt_type
     *
     * @return the value of h_roomtype.rt_type
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public String getRtType() {
        return rtType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_roomtype.rt_type
     *
     * @param rtType the value for h_roomtype.rt_type
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setRtType(String rtType) {
        this.rtType = rtType == null ? null : rtType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_roomtype.rt_stock
     *
     * @return the value of h_roomtype.rt_stock
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Integer getRtStock() {
        return rtStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_roomtype.rt_stock
     *
     * @param rtStock the value for h_roomtype.rt_stock
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setRtStock(Integer rtStock) {
        this.rtStock = rtStock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column h_roomtype.rt_price
     *
     * @return the value of h_roomtype.rt_price
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public Integer getRtPrice() {
        return rtPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column h_roomtype.rt_price
     *
     * @param rtPrice the value for h_roomtype.rt_price
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    public void setRtPrice(Integer rtPrice) {
        this.rtPrice = rtPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_roomtype
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        H_Roomtype other = (H_Roomtype) that;
        return (this.getRtId() == null ? other.getRtId() == null : this.getRtId().equals(other.getRtId()))
            && (this.getHotelId() == null ? other.getHotelId() == null : this.getHotelId().equals(other.getHotelId()))
            && (this.getRtType() == null ? other.getRtType() == null : this.getRtType().equals(other.getRtType()))
            && (this.getRtStock() == null ? other.getRtStock() == null : this.getRtStock().equals(other.getRtStock()))
            && (this.getRtPrice() == null ? other.getRtPrice() == null : this.getRtPrice().equals(other.getRtPrice()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_roomtype
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getRtId() == null) ? 0 : getRtId().hashCode());
        result = prime * result + ((getHotelId() == null) ? 0 : getHotelId().hashCode());
        result = prime * result + ((getRtType() == null) ? 0 : getRtType().hashCode());
        result = prime * result + ((getRtStock() == null) ? 0 : getRtStock().hashCode());
        result = prime * result + ((getRtPrice() == null) ? 0 : getRtPrice().hashCode());
        return result;
    }
}