package net.suncaper.hotel_manager.mapper;

import java.util.List;
import net.suncaper.hotel_manager.domain.H_Admin;
import net.suncaper.hotel_manager.domain.H_AdminExample;
import org.apache.ibatis.annotations.Param;

public interface H_AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    long countByExample(H_AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int deleteByExample(H_AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int deleteByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int insert(H_Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int insertSelective(H_Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    List<H_Admin> selectByExample(H_AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    H_Admin selectByPrimaryKey(Integer aId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") H_Admin record, @Param("example") H_AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByExample(@Param("record") H_Admin record, @Param("example") H_AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByPrimaryKeySelective(H_Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_admin
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByPrimaryKey(H_Admin record);
}