package net.suncaper.hotel_manager.mapper;

import java.util.List;
import net.suncaper.hotel_manager.domain.H_Hotel;
import net.suncaper.hotel_manager.domain.H_HotelExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface H_HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    long countByExample(H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    int deleteByExample(H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    int deleteByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    int insert(H_Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    int insertSelective(H_Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    List<H_Hotel> selectByExampleWithBLOBs(H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    List<H_Hotel> selectByExample(H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    H_Hotel selectByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    int updateByExampleSelective(@Param("record") H_Hotel record, @Param("example") H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") H_Hotel record, @Param("example") H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    int updateByExample(@Param("record") H_Hotel record, @Param("example") H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    int updateByPrimaryKeySelective(H_Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(H_Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Thu Jul 25 14:18:49 CST 2019
     */
    int updateByPrimaryKey(H_Hotel record);

    @Select("SELECT hotel_id, hotel_translated_name, addressline FROM h_hotel LIMIT (0, 10)")
    List<H_Hotel> selectIdAndName();

    @Select("SELECT hotel_translated_name, addressline, star_rating, url, numberrooms, numberfloor, yearopened," +
            "photo1, photo2, photo3, overview, rating_average FROM h_hotel WHERE hotel_id = #{hotel_id}")
    H_Hotel selectHotelInfo(@Param("hotel_id") int hotel_id);

}