package net.suncaper.hotel_manager.mapper;

import java.util.List;
import net.suncaper.hotel_manager.domain.H_Hotel;
import net.suncaper.hotel_manager.domain.H_HotelExample;
import org.apache.ibatis.annotations.Param;

public interface H_HotelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    long countByExample(H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int deleteByExample(H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int deleteByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int insert(H_Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int insertSelective(H_Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    List<H_Hotel> selectByExampleWithBLOBs(H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    List<H_Hotel> selectByExample(H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    H_Hotel selectByPrimaryKey(Integer hotelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") H_Hotel record, @Param("example") H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByExampleWithBLOBs(@Param("record") H_Hotel record, @Param("example") H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByExample(@Param("record") H_Hotel record, @Param("example") H_HotelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByPrimaryKeySelective(H_Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByPrimaryKeyWithBLOBs(H_Hotel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_hotel
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByPrimaryKey(H_Hotel record);
}