package net.suncaper.hotel_manager.mapper;

import java.util.List;
import net.suncaper.hotel_manager.domain.H_Room;
import net.suncaper.hotel_manager.domain.H_RoomExample;
import org.apache.ibatis.annotations.Param;

public interface H_RoomMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    long countByExample(H_RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int deleteByExample(H_RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int deleteByPrimaryKey(Integer rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int insert(H_Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int insertSelective(H_Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    List<H_Room> selectByExample(H_RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    H_Room selectByPrimaryKey(Integer rId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") H_Room record, @Param("example") H_RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByExample(@Param("record") H_Room record, @Param("example") H_RoomExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByPrimaryKeySelective(H_Room record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_room
     *
     * @mbg.generated Wed Aug 07 17:59:24 CST 2019
     */
    int updateByPrimaryKey(H_Room record);
}