package net.suncaper.hotel_manager.mapper;

import java.util.List;
import net.suncaper.hotel_manager.domain.H_User;
import net.suncaper.hotel_manager.domain.H_UserExample;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface H_UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user
     *
     * @mbg.generated Thu Jul 25 14:17:35 GMT+08:00 2019
     */
    long countByExample(H_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user
     *
     * @mbg.generated Thu Jul 25 14:17:35 GMT+08:00 2019
     */
    int deleteByExample(H_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user
     *
     * @mbg.generated Thu Jul 25 14:17:35 GMT+08:00 2019
     */
    int deleteByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user
     *
     * @mbg.generated Thu Jul 25 14:17:35 GMT+08:00 2019
     */
    int insert(H_User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user
     *
     * @mbg.generated Thu Jul 25 14:17:35 GMT+08:00 2019
     */
    int insertSelective(H_User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user
     *
     * @mbg.generated Thu Jul 25 14:17:35 GMT+08:00 2019
     */
    List<H_User> selectByExample(H_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user
     *
     * @mbg.generated Thu Jul 25 14:17:35 GMT+08:00 2019
     */
    H_User selectByPrimaryKey(Integer uId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user
     *
     * @mbg.generated Thu Jul 25 14:17:35 GMT+08:00 2019
     */
    int updateByExampleSelective(@Param("record") H_User record, @Param("example") H_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user
     *
     * @mbg.generated Thu Jul 25 14:17:35 GMT+08:00 2019
     */
    int updateByExample(@Param("record") H_User record, @Param("example") H_UserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user
     *
     * @mbg.generated Thu Jul 25 14:17:35 GMT+08:00 2019
     */
    int updateByPrimaryKeySelective(H_User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table h_user
     *
     * @mbg.generated Thu Jul 25 14:17:35 GMT+08:00 2019
     */
    int updateByPrimaryKey(H_User record);

    //**************************DIY***********************//
    @Select("select u_id from h_user where u_account = #{u_account} and u_password = #{u_password}")
     H_User selectByAccountAndPwd(String u_account,String u_password);

    @Select("select u_id from h_user where u_account = #{u_account}")
    H_User selectByAccount(String u_account);
}